name: lynks

services:
    postgres:
        image: postgres:18-trixie
        restart: always
        volumes:
            - lynks-data:/var/lib/postgresql
        env_file:
            - config/.env
        environment:
            - POSTGRES_DB=lynksdb
            - POSTGRES_USER=lynksuser
        ports:
            - '127.0.0.1:5432:5432'

volumes:
    lynks-data:
