services:
  postgres:
    image: postgres
    restart: unless-stopped
    volumes:
      - lynks-data:/var/lib/postgresql/data
    env_file:
      - ./config/.env
    environment:
      - POSTGRES_DB=lynksdb
      - POSTGRES_USER=lynksuser
    ports:
      - '5432:5432'
volumes:
  lynks-data:
