services:
  lynks-ui:
    image: raharrison/lynks-ui:1.2.2
    restart: on-failure:5
  lynks-server:
    image: raharrison/lynks-server:1.3.4
    env_file:
      - ./config/.env
    environment:
      - JAVA_OPTS=-DCONFIG_MODE=prod
      - external_scraperHost=http://lynks-scraper:3000/api
      - database_user=${POSTGRES_USER:-lynksuser}
      - database_password=${POSTGRES_PASSWORD}
      - database_url=jdbc:postgresql://postgres:5432/${POSTGRES_DB:-lynksdb}
    volumes:
      - ./media:/app/media
      - ./config:/app/config
    user: ${CURRENT_UID:-0}:${CURRENT_GUID:-0}
    restart: on-failure:5
    depends_on:
      - postgres
  lynks-scraper:
    image: raharrison/lynks-scraper:1.0.3
    init: true
    restart: on-failure:5
    volumes:
      - ./media:/app/media
    user: ${CURRENT_UID:-0}:${CURRENT_GUID:-0}
  lynks-gateway:
    image: nginx:1.21-alpine
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: on-failure:5
    ports:
      - "127.0.0.1:8090:80"
    depends_on:
      - lynks-ui
      - lynks-server
  postgres:
    image: postgres:14-bullseye
    volumes:
      - lynks-data:/var/lib/postgresql/data
    restart: on-failure:5
    env_file:
      - ./config/.env
    ports:
      - '127.0.0.1:5432:5432'

volumes:
  lynks-data:
